vaadin.launch-browser=true
spring.application.name=tp_Final

# PostgreSQL config
spring.datasource.url=jdbc:postgresql://localhost:5432/terceros01
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=1243



# JPA config
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

